### ISSUE TITLE
Khi thêm nhân sự, cần kiểm tra, nếu chưa có bộ phận nào thì cần thông báo, chuyển hướng đến trang thêm bộ phận

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/module-workforce#3]

**Comment by huuthoqt1994** [comment]
Đã fix https://github.com/huuthoqt1994/module-workforce/commit/a0eba48330cc07697d9f4855efd80ce556334919 & https://github.com/huuthoqt1994/module-workforce/commit/53942c2d63e3de385646efd610ca42017c1c7c30
