### ISSUE TITLE
Thiếu lang trang quản lý bộ phận

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/module-workforce#4]
![image](https://user-images.githubusercontent.com/6407361/45857110-884d5380-bd81-11e8-8c68-01ccd4ba32e5.png)

**Comment by mynukeviet** [comment]
Chỉnh độ rộng cột lại cho hợp lý

![screenshot from 2018-09-21 09-36-56](https://user-images.githubusercontent.com/6407361/45857209-ea0dbd80-bd81-11e8-996e-1f32ab8bdd1d.png)

**Comment by huuthoqt1994** [comment]
Đã fix +https://github.com/huuthoqt1994/module-workforce/commit/8d11a134c2210ceb7117800f6215bb0dc4f3e680
